# Generated by Django 6.0.1 on 2026-01-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0002_resident_gender_alter_resident_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
