# Generated by Django 6.0.1 on 2026-01-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='gender',
            field=models.CharField(blank=True, default='Not specified', max_length=10),
        ),
        migrations.AlterField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
