# Generated by Django 6.0.1 on 2026-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0003_resident_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
