# Generated by Django 6.0.1 on 2026-01-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0004_resident_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
